### ISSUE TITLE
Resolution issue.

### ISSUE THREAD

**Issue by Chojnackii** [TomGrobbe/vMenu#120] opened 2018-09-08 08:06 UTC
Resolution issue is still on v1.20, still boxing :/ Any helps?

**Comment by TomGrobbe** [comment] 2018-09-08 10:15
@Chojnackii Still boxing?

**Comment by TomGrobbe** [comment] 2018-09-08 10:30
@Chojnackii That has nothing to do with resolution though, and this is apparently caused by having bad map resources

**Comment by Chojnackii** [comment] 2018-09-08 10:32
Map resource? Which  map is  Good ?

**Comment by TomGrobbe** [comment] 2018-09-08 10:33
@Chojnackii Idk, but most users with this problem solved it by removing custom maps

**Comment by Chojnackii** [comment] 2018-09-08 10:34
Hmmm  i don't have custom  map. Just the original  one

**Comment by TomGrobbe** [comment] 2018-09-08 10:34
@Chojnackii Then idk.

**Comment by Chojnackii** [comment] 2018-09-08 10:36
Okay i'll search fix  for this.

**Comment by TomGrobbe** [comment] 2018-09-09 17:38
Closing this because it's not really a resolution issue, and most likely not caused by vMenu. If you have new info about this, then feel free to reply to this and I'll consider re-opening it if it does turn out to be caused by vMenu.

**Closed** 2018-09-09 17:37 UTC
