### ISSUE TITLE
Invisible skins

### ISSUE THREAD

**Issue by matty45** [TomGrobbe/vMenu#89] opened 2018-05-14 16:43 UTC
When someone changes their skin. It appears on their end but makes the player invisible to all the other players.

![Image](https://i.imgur.com/lae7ivz.png)

**Comment by TomGrobbe** [comment] 2018-05-14 16:52
Seems to be completely random. Because I've tested multiple skins that players reported but it always seems to work fine for me. Any particular skin that bugs out for you?

**Comment by matty45** [comment] 2018-05-14 16:53
No idea, dont know what skin caused that player to be invisible

**Comment by itismejoey** [comment] 2018-05-14 16:54
Unknown if it's related or not, but I tried to spawn a saved skin and I was invisible for about 15 seconds before my ped finally appeared.

**Comment by TomGrobbe** [comment] 2018-05-14 16:55
> Unknown if it's related or not, but I tried to spawn a saved skin and I was invisible for about 15 seconds before my ped finally appeared. No one was around me, so I can't confirm if I was invisible for other people as well.

was this using an addon/replacement ped? or just a regular ped?

**Comment by matty45** [comment] 2018-05-14 16:56
for me, it was a regular ped

**Comment by itismejoey** [comment] 2018-05-14 16:56
Same way that I spawned my peds from when I explained in The Discord channel. Using the default MP Male Ped and then using Skin Control (and eventually vMenu) to edit/save/spawn.

**Comment by matty45** [comment] 2018-05-14 16:59
im wondering if its because the player changed his skin far away from me

**Comment by TomGrobbe** [comment] 2018-05-14 17:25
just checked, and vMenu is using the same approach as lambda menu when it comes to switching skins, it also resets ped customization after changing skins so it should work just fine... Maybe this happens when switching skins very quickly? Can't fix this anyway if I'm not able to reproduce this. If you have some steps that lead to this issue every single time, on multiple servers running vMenu, then let me know so I can try to recreate the issue, but until then I'll close this issue as I can't reproduce it myself.

**Closed by TomGrobbe** 2018-05-14 17:25 UTC
