### ISSUE TITLE
Resource time warning

### ISSUE THREAD

**Issue by rayyanallaf** [TomGrobbe/vMenu#181] opened 2019-04-29 11:44 UTC
**Describe the bug**
Hey, so out of no where my vMenu has been acting up. Every player on my server has been receiving this. I can open the menu but it’s impossible to play when im getting this resource time warning from vMenu. Anyone know how to fix this? https://gyazo.com/ddae13b5be4dcf57c90a4adcb7ae4714 4

**To Reproduce**
1. On the bottom right if the screen you see a time warning for vmenu making everyone lose 50 fps
2. Then when  I press 8 it shows the pool size error.

**Expected behavior**
Out if no where kt started happening si we decided to update it to the newest version and the menu wont even open. It said there is a problem with the vmenuserver.dll

**vMenu Info**:
- Server ip: 142.44.218.20:30138
 vMenu Version (check the about menu): 2.22
- Do you have access to the files?
Yes
- FXServer artifacts version:

**Additional context**
Such as:

- A list of allowed permissions for the player that is having this issue. Everyone
- A list of enabled/disabled vMenu features.

Both of these can very easily be provided by using `/vmenuclient dump` while in-game and sending the CitizenFX.log file (`FiveM Application Data\CitizenFX.log`) from that same game session.

**Comment by TomGrobbe** [comment] 2019-04-29 12:09
this is caused by outdated versions of the manual transmission (gears V) client side mod. This can't be fixed by me, tell your players to update their client side manual transmission mods, or any other mod that may set decorators incorrectly. If you have scripthook disabled, then it must be another resource that you installed which manages decorators completely wrong and thus breaks the game (and vMenu) in the process.

**Comment by TomGrobbe** [comment] 2019-04-29 12:11
Side note: the server version is horribly outdated (**really** old version). And the fact that you have 230+ resources also doesn't help.

**Closed** 2019-05-05 20:42 UTC
