### ISSUE TITLE
Menu moves position randomly

### ISSUE THREAD

**Issue by Rainman85** [TomGrobbe/vMenu#100] opened 2018-06-06 14:08 UTC
Hey Tom, just want to say firstly that you did an awesome job with this. We love it.

Anyway there seems to be an issue with the menu moving position. For example, it could be on the top left corner when i log in and then next time i log in it could be on the top right hand corner. Me and my friends were testing it yesterday and all noticed this behavior.

**Comment by TomGrobbe** [comment] 2018-06-06 14:14
@Rainman85 Menu can change position if you. A) change resolutions. B) switch full screen/windowed/borderless mode. C) you have a weird resolution that gta doesn’t support by default.

It’s a known issue and can’t be fixed in vMenu. Needs to be fixed in nativeui itself as the resolutions there are hardcoded. To solve this, use windowed borderless or fullscreen mode instead of windowed, and don’t switch those modes/change resolutions when you’re ingame.

**Comment by TomGrobbe** [comment] 2018-06-06 14:15
@Rainman85 Menu is supposed to be on the right. So whenever it’s on the left, then it’s one of the causes above.

**Comment by Rainman85** [comment] 2018-06-06 15:20
@TomGrobbe  BTW...is it possible to have it stay in the top left position?

**Closed** 2018-06-06 15:29 UTC
